- name: 生成硬件报告
  hosts: all
  tasks:
          - name: geturl
            get_url:
                    url: http://materials/hwreport.empty
                    dest: /root/hwreport.txt
          - name: inventoryhostname
            replace:
                    path: /root/hwreport.txt
                    regexp: inventoryhostname
                    replace: "{{ inventory_hostname }}"
          - name: memory_in_MB
            replace:
                    path: /root/hwreport.txt
                    regexp: memory_in_MB
                    replace: "{{ ansible_memtotal_mb | string }}"
          - name: BIOS_version
            replace:
                    path: /root/hwreport.txt
                    regexp: BIOS_version
                    replace: "{{ ansible_bios_version }}"
          - name: disk_vda_size
            replace:
                    path: /root/hwreport.txt
                    regexp: disk_vda_size
                    replace: "{{ ansible_devices.vda.size | default('NONE') }}"
          - name: disk_vdb_size
            replace:
                    path: /root/hwreport.txt
                    regexp: disk_vdb_size
                    replace: "{{ ansible_devices.vdb.size | default('NONE') }}"
